name: Update Packages file

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Generate Packages
      run: dpkg-scanpackages -m repo/deb /dev/null > repo/Packages

    - name: Generate Packages.gz
      run: gzip -9kc repo/Packages > repo/Packages.gz

    - name: Generate Packages.xz
      run: xz -9kc repo/Packages > repo/Packages.xz

    - name: Generate Packages.bz2
      run: bzip2 -9k repo/Packages
