name: Update Packages file

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev

    - name: Remove old files
      run: rm -f repo/Packages repo/Packages.xz repo/Packages.gz repo/Packages.bz2

    - name: Generate Packages
      run: dpkg-scanpackages -m repo/deb /dev/null > repo/Packages

    - name: Generate Packages.gz
      run: gzip -9k repo/Packages

    - name: Generate Packages.xz
      run: xz -9k repo/Packages

    - name: Generate Packages.bz2
      run: bzip2 -9k repo/Packages

    - name: Commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add repo/Packages repo/Packages.xz repo/Packages.gz repo/Packages.bz2
        git commit -m "auto update Packages files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
